[tool.poetry]
name = "bring-back-rex"
version = "0.1.0"
description = ""
authors = ["vadimkopylov <kopylov.ddut@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
